export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const DELETE_SELECTED_QUESTION = "DELETE_SELECTED_QUESTION";

export const FETCH_QUESTION = "FETCH_QUESTION";
export const SET_SELECTED_QUESTION = "SET_SELECTED_QUESTION";
