export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const BACK_FROM_SELECTED_QUESTION = "BACK_FROM_SELECTED_QUESTION";

export const GET_QUESTION_BY_PAGE_NUMBER = "GET_QUESTION_BY_PAGE_NUMBER"; // Бүх асуултуудыг авах
export const SET_SELECTED_QUESTION = "SET_SELECTED_QUESTION"; // сонгогдсон асуултыг ХАДГАЛАХ
export const SET_SELECTED_QUESTION_FOR_VOTE = "SET_SELECTED_QUESTION_FOR_VOTE"; // сонгогдсон асуултыг ХАДГАЛАХ
export const CREATE_QUESTION_TOGGLE = "CREATE_QUESTION_TOGGLE"; //
export const UPDATE_QUESTION_TOGGLE = "UPDATE_QUESTION_TOGGLE"; //
export const DELETE_SELECTED_QUESTION = "DELETE_SELECTED_QUESTION";
export const UPDATE_SELECTED_QUESTION = "UPDATE_SELECTED_QUESTION";
export const SET_QUESTION_PAGE = "SET_QUESTION_PAGE";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const VOTE_SELECTED_QUESTION = "VOTE_SELECTED_QUESTION";

// * COMMENTS
export const GET_COMMENTS_BY_PAGE_NUMBER = "GET_COMMENTS_BY_PAGE_NUMBER";
export const VOTE_COMMENT = "VOTE_COMMENT";
export const SEND_COMMENT = "SEND_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const UPDATE_COMMENT_TOGGLE = "UPDATE_QUESTION_TOGGLE";
// GET_QUESTION_BY_PAGE_NUMBER;
export const SET_IMAGE_URL = "SET_IMAGE_URL";
export const SET_HTML_STRING = "SET_HTML_STRING";
