export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const BACK_FROM_SELECTED_QUESTION = "BACK_FROM_SELECTED_QUESTION";

export const FETCH_QUESTION = "FETCH_QUESTION"; // Бүх асуултуудыг авах
export const SET_SELECTED_QUESTION = "SET_SELECTED_QUESTION"; // сонгогдсон асуултыг ХАДГАЛАХ
export const CREATE_QUESTION_TOGGLE = "CREATE_QUESTION_TOGGLE"; // Create question FROM харагдац toggle hiih
export const DELETE_SELECTED_QUESTION = "DELETE_SELECTED_QUESTION";
export const UPDATE_SELECTED_QUESTION = "UPDATE_SELECTED_QUESTION";
// deleteSelectedQuestion;DELETE_SELECTED_QUESTION
export const CREATE_QUESTION = "CREATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
